# -*- coding: utf-8 -*-
"""BT_SHEET1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_NkWxCyDYvYwBDkz8_4VlcLPp17026R
"""

from google.colab import files
import pandas as pd

# Bước 1: Upload file
uploaded = files.upload("C:\Users\PC\OneDrive\Tài liệu\GitHub\Group-2\games.csv")

import pandas as pd
import matplotlib.pyplot as plt

# Đọc dữ liệu
file_path = '/mnt/data/games.csv'
data = pd.read_csv('games.csv')

# Chọn dữ liệu để vẽ
top_games = data.head(10)  # Lấy 10 game đầu tiên
titles = top_games['Title']
ratings = top_games['Rating']
plays = top_games['Plays'].str.replace('K', '').str.replace('.', '').astype(int) * 1000  # Xử lý Plays thành số
# Remove 'K' and '.' before converting to int and then multiply by 1000
genres = top_games['Genres'].apply(lambda x: eval(x)[0])  # Lấy thể loại đầu tiên

# 1. Biểu đồ cột: Rating của top 10 game
plt.figure(figsize=(10, 6))
plt.bar(titles, ratings, color='skyblue')
plt.title('Top 10 Game Ratings')
plt.xlabel('Game')
plt.ylabel('Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 2. Biểu đồ đường: Số lần chơi của top 10 game
plt.figure(figsize=(10, 6))
plt.plot(titles, plays, marker='o', linestyle='-', color='orange')
plt.title('Number of Plays for Top 10 Games')
plt.xlabel('Game')
plt.ylabel('Plays')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.tight_layout()
plt.show()

# 3. Biểu đồ tròn: Phân phối thể loại của top 10 game
genre_counts = genres.value_counts()
plt.figure(figsize=(8, 8))
plt.pie(genre_counts, labels=genre_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.tab20.colors)
plt.title('Genre Distribution of Top 10 Games')
plt.show()